Migration of articles from Evmos Docs
evmos/academy pull request #29
Opened 2023-08-04 15:52 UTC by lmedury

The following updates were made in this PR: 

- Articles from Evmos Docs have been included in Academy
- README.md file includes instructions with illustrations to contribute to the academy repository
- Removed FAQ article in articles/beginner

2023-08-04 16:08 UTC, 0xstepit commented on README.md
> +`code .`
I wouldn't put here this command since for example, on VSC, you should have enabled it. So, it is not general.

2023-08-04 16:09 UTC, 0xstepit commented on README.md
> +A brief intro to markdown:
We could link to markdown doc here

2023-08-04 16:11 UTC, 0xstepit commented on docs/articles/advanced/validate.md
> +
remove ws

2023-08-04 16:18 UTC, 0xstepit reviewed
Titles style are not homogeneous. Please choose only one between "Title Like This One" or "Title like this one".

2023-08-04 16:20 UTC, 0xstepit commented
@lmedury many thanks for your contribution :) would be great if you can fix Markdown Linter errors so we can have everything homogeneous.

2023-08-10 14:20 UTC, lmedury commented
> @lmedury many thanks for your contribution :) would be great if you can fix Markdown Linter errors so we can have everything homogeneous.

Thank you @0xstepit for your very helpful detailed feedback. Please review my latest commit when you get a chance.

2023-08-16 18:26 UTC, GAtom22 requested changes
Thanks @lmedury !! 
Please address the lint issues and the dead links

2023-10-17 17:36 UTC, danburck commented
@lmedury Thanks for this! Some changes are still required, as it looks like more articles were ported than expected. 


**Ported to many articles**
Right now this PR includes articles from the Evmos [Develop](https://docs.evmos.org/develop) and [Protocol](https://docs.evmos.org/protocol) sections.

Please reduce the scope of this PR to only porting over articles from the [Evmos Docs Use](https://docs.evmos.org/use) section to the Academy beginner section. Note to keep the folder structure as given in the docs (i.e. keep Keplr, Metamask and Ledger under `Connect your wallet`)

This includes the following sections, see screenshot
<img width="235" alt="Screenshot 2023-10-17 at 19 30 25" src="https://github.com/evmos/academy/assets/33006856/984e677a-6d03-4e0f-ac3e-fbb0fe5f5a4d">

**Button design**
There is a custom Button design that has been created on the Evmos docs. Can you port that design over to the academy? 

Check the example in this screenshot of the Metamask page

<img width="976" alt="Screenshot 2023-10-17 at 19 35 54" src="https://github.com/evmos/academy/assets/33006856/9cbe3390-1d2d-4592-8dc5-da6c6261826a">

2023-11-10 16:18 UTC, danburck approved these changes

2023-11-10 16:21 UTC, merged